### ISSUE TITLE
Unable to run the project.

### ISSUE THREAD

**Issue by tatupesonen** [scarvalhojr/aocleaderboard#1]
Hello maintainer!

I'm trying to dockerize your application. I'm having an issue with trying to run it.
![image](https://user-images.githubusercontent.com/7150217/144456184-dcc90cf3-cad2-4b15-a0cc-e08ab3674378.png)
This is the error I get. I've added leaderboard IDs I have access to to `settings.toml` and added my cookie to the session.

I've tried on WSL2 with the following rustc versions:
`rustc 1.59.0-nightly (6db0a0e9a 2021-11-29)`
`rustc 1.59.0-nightly (48a5999fc 2021-12-01)`

I also thought it was a WSL2 issue, so I ran it on Windows with the following rustc version:
`rustc 1.59.0-nightly (48a5999fc 2021-12-01)`

Lastly, I'm on commit cd846ecb92313566cd3884a223131d97bed5c453 of the repository.

**Comment by tatupesonen** [comment]
I've reverted the repository back to c2d13d54b3e97e4b9709e0c06072d22aa45c1b05 and that seems to work.

**Comment by scarvalhojr** [comment]
Sorry, it looks like updating `reqwest` to 0.11 needs a little change in the code. I've reverted it to 0.10 for now.
